environment: development

apphost: k8s

label:
  name: helmtutorial

container:
  frontEndName: k8sfrontend
  backEndName: k8sbackend
  pullPolicy: IfNotPresent
  frontEndImage: codingflamingoacr.azurecr.io/k8sfrontend
  backEndImage: codingflamingoacr.azurecr.io/k8sbackend
  namespace: devcodingflamingo 
  frontEndTag: v7
  backEndTag: v3
  frontEndport: 80
  frontEndServiceport: 9778
  backEndport: 80
  backEndServiceport: 9368
frontEndreplicas: 1
backEndreplicas: 1

certificate:
  appdnsname: flamingo.westus2.cloudapp.azure.com
  certtype: letsencrypt-staging
  email: codingflamingo@gmail.com
  certserver: https://acme-staging-v02.api.letsencrypt.org/directory
service:
  port: 8888
  type: ClusterIP
