apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.certificateName }}
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ .Values.certificate.certificateName }}
  dnsNames:
    - {{ .Values.certificate.appDNSName }}
  issuerRef:
    name: {{ .Values.certificate.certType }}
    kind: ClusterIssuer

