apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sampleapp-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.certificate.ingressClass }}
    cert-manager.io/cluster-issuer: {{ .Values.certificate.certType }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/proxy-set-header: |
      X-Forwarded-Proto $scheme
      X-Forwarded-For $remote_addr
      X-Forwarded-Host $host
spec:
  ingressClassName: {{ .Values.certificate.ingressClass }}
  tls:
  - hosts:
    - {{ .Values.certificate.appDNSName }}
    secretName: {{ .Values.certificate.certificateName }}
  rules:
  - host: {{ .Values.certificate.appDNSName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.sampleapp.name }}-service
            port:
              number: {{ .Values.sampleapp.frontEndportServicePort }}